FROM openjdk:8-jdk-alpine

RUN apk add --no-cache curl

WORKDIR /usr/local/bin

COPY ./build/libs/helloworld*.jar /app.jar

CMD java \
    -Dserver.port=80 \
    -jar \
    /app.jar

EXPOSE 80

HEALTHCHECK --start-period-15s --interval=15s CMD["curl", "localhost:80/health"]